# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](bg:color_group1)\
$os\
$username\
$hostname\
[](fg:color_group1 bg:color_group2)\
$directory\
[](fg:color_group2 bg:color_group3)\
$git_branch\
$git_status\
[](fg:color_group3 bg:color_group4)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_group4 bg:color_group5)\
$docker_context\
$conda\
[](fg:color_group5 bg:color_group6)\
$cmd_duration\
$time\
[ ](fg:color_group6)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#ffffff'
color_fg1 = '#1c1c1c'
color_green = '#98971a'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

# color_group1 = '#d65d0e'
color_group1 = '#d79921'
color_group2 = '#5f5faa'
color_group3 = '#689d6a'
color_group4 = '#458588'
# color_group4 = '#8be9fd'
color_group5 = '#665c54'
color_group6 = '#3c3836'

[os]
disabled = false
style = "bg:color_group1 fg:color_fg0"

[os.symbols]
Windows = "󰍲 "
Ubuntu = " "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[username]
show_always = false
style_user = "bg:color_group1 fg:color_fg0"
style_root = "bg:color_group1 fg:color_fg0"
format = '[$user]($style)'

[hostname]
ssh_only = true
style = "bg:color_group1 fg:color_fg0"
format = '[@$hostname ]($style)'

[directory]
style = "fg:color_fg0 bg:color_group2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_group3"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_group3)]($style)'

[git_status]
style = "bg:color_group3"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_group3)]($style)'

[nodejs]
symbol = ""
style = "bg:color_group4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_group4)]($style)'

[c]
symbol = " "
style = "bg:color_group4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_group4)]($style)'

[rust]
symbol = ""
style = "bg:color_group4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_group4)]($style)'

[golang]
symbol = ""
style = "bg:color_group4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_group4)]($style)'

[php]
symbol = ""
style = "bg:color_group4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_group4)]($style)'

[java]
symbol = " "
style = "bg:color_group4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_group4)]($style)'

[kotlin]
symbol = ""
style = "bg:color_group4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_group4)]($style)'

[haskell]
symbol = ""
style = "bg:color_group4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_group4)]($style)'

[python]
symbol = ""
style = "bg:color_group4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_group4)]($style)'

[docker_context]
symbol = ""
style = "bg:color_group5"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_group5)]($style)'

[conda]
style = "bg:color_group5"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_group5)]($style)'

[cmd_duration]
format = "[ 󰔛 $duration ]($style)"
style = "fg:color_fg0 bg:color_group6"

[time]
disabled = false
time_format = "%R"
style = "bg:color_group6"
format = '[[  $time ](fg:color_fg0 bg:color_group6)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_green)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[❮](bold fg:color_green)'
vimcmd_replace_one_symbol = '[❮](bold fg:color_purple)'
vimcmd_replace_symbol = '[❮](bold fg:color_purple)'
vimcmd_visual_symbol = '[❮](bold fg:color_yellow)'
